import { StyleSheet } from "react-native";
import { fonts } from "@/theme/typography";

/** Общие стили bottom-sheet модалок профиля (как InfoNoticeModal). */
export const profileBottomSheetStyles = StyleSheet.create({
  backdrop: { flex: 1, justifyContent: "flex-end" },
  sheet: {
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    padding: 20,
    paddingBottom: 28,
    maxHeight: "85%",
  },
  title: { fontFamily: fonts.extraBold, fontSize: 18, marginBottom: 12 },
  hint: { fontFamily: fonts.regular, fontSize: 14, lineHeight: 20, marginBottom: 12 },
  sectionTitle: { fontFamily: fonts.bold, fontSize: 16, marginBottom: 10, marginTop: 4 },
  input: {
    fontFamily: fonts.regular,
    fontSize: 16,
    borderWidth: 1,
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 12,
    marginBottom: 8,
  },
  err: { fontFamily: fonts.regular, fontSize: 13, marginBottom: 8 },
  actionRow: { flexDirection: "row", gap: 12, marginTop: 16 },
  ghostBtn: { paddingVertical: 14, paddingHorizontal: 8, justifyContent: "center" },
  ghostBtnText: { fontFamily: fonts.semiBold, fontSize: 16 },
  primaryBtn: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    minHeight: 48,
  },
  primaryBtnText: { fontFamily: fonts.bold, fontSize: 16, color: "#FFFFFF" },
  statsRow: { flexDirection: "row", flexWrap: "wrap", gap: 10, marginBottom: 16 },
  statCard: {
    flexGrow: 1,
    flexBasis: "30%",
    minWidth: 96,
    borderRadius: 14,
    paddingVertical: 12,
    paddingHorizontal: 10,
    alignItems: "center",
    borderWidth: StyleSheet.hairlineWidth,
  },
  statValue: { fontFamily: fonts.extraBold, fontSize: 22, marginTop: 4 },
  statLabel: { fontFamily: fonts.regular, fontSize: 11, textAlign: "center", lineHeight: 14 },
  codeBox: { borderRadius: 14, padding: 14, marginBottom: 12, alignItems: "center" },
  codeLabel: { fontFamily: fonts.regular, fontSize: 12, marginBottom: 6 },
  code: { fontFamily: fonts.extraBold, fontSize: 22, letterSpacing: 2 },
  btnRow: { flexDirection: "row", gap: 10, marginBottom: 8 },
  iconBtn: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    paddingVertical: 12,
    borderRadius: 14,
    borderWidth: StyleSheet.hairlineWidth,
  },
  iconBtnText: { fontFamily: fonts.semiBold, fontSize: 14 },
});
