import { StyleSheet } from "react-native";
import { PLAQUE_RADIUS, plaqueListShadow } from "@/theme/plaqueStyles";
import type { useAppTheme } from "@/theme/appTheme";
import { fonts, type } from "@/theme/typography";

export function createPlansScreenStyles(theme: ReturnType<typeof useAppTheme>) {
  return StyleSheet.create({
    scroll: {
      flex: 1,
      backgroundColor: theme.bg,
    },
    scrollContent: {
      paddingBottom: 8,
    },
    screenTitle: {
      fontFamily: fonts.semiBold,
      fontSize: 28,
      lineHeight: 34,
      color: theme.text,
      letterSpacing: -0.5,
      marginBottom: 16,
    },
    mockBadge: {
      alignSelf: "flex-start",
      paddingHorizontal: 10,
      paddingVertical: 4,
      borderRadius: 999,
      backgroundColor: theme.accentSoft,
      marginBottom: 16,
    },
    mockBadgeText: {
      fontFamily: fonts.medium,
      fontSize: 12,
      lineHeight: 16,
      color: theme.accent,
    },
    tabsWrap: {
      marginBottom: 16,
    },
    sectionBlock: {
      marginBottom: 4,
    },
    card: {
      borderRadius: PLAQUE_RADIUS,
      backgroundColor: theme.card,
      paddingHorizontal: 16,
      paddingVertical: 14,
      marginBottom: 12,
      ...plaqueListShadow(),
    },
    sectionTitle: {
      ...type.section,
      fontSize: 17,
      lineHeight: 22,
      fontFamily: fonts.semiBold,
      color: theme.text,
      marginBottom: 12,
    },
    sectionTitleInline: {
      marginBottom: 0,
    },
    quickActionsRow: {
      flexDirection: "row",
      gap: 10,
      marginBottom: 16,
    },
    quickAction: {
      flex: 1,
      borderRadius: PLAQUE_RADIUS,
      backgroundColor: theme.card,
      paddingVertical: 14,
      paddingHorizontal: 12,
      alignItems: "flex-start",
      gap: 6,
      ...plaqueListShadow(),
    },
    quickActionLabel: {
      fontFamily: fonts.semiBold,
      fontSize: 14,
      lineHeight: 18,
      color: theme.text,
    },
    quickActionSub: {
      fontFamily: fonts.regular,
      fontSize: 12,
      lineHeight: 16,
      color: theme.textMuted,
    },
    weekStrip: {
      flexDirection: "row",
      justifyContent: "space-between",
      marginBottom: 16,
      gap: 4,
    },
    weekDayCell: {
      flex: 1,
      alignItems: "center",
      paddingVertical: 10,
      borderRadius: 12,
      minWidth: 0,
    },
    weekDayCellSelected: {
      backgroundColor: theme.accentSoft,
    },
    weekDayLabel: {
      fontFamily: fonts.medium,
      fontSize: 11,
      lineHeight: 14,
      color: theme.textMuted,
      textTransform: "lowercase",
    },
    weekDayLabelSelected: {
      color: theme.accent,
      fontFamily: fonts.semiBold,
    },
    weekDayNumber: {
      marginTop: 4,
      fontFamily: fonts.semiBold,
      fontSize: 16,
      lineHeight: 20,
      color: theme.text,
    },
    weekDayNumberSelected: {
      color: theme.accent,
    },
    weekDayDot: {
      marginTop: 4,
      width: 6,
      height: 6,
      borderRadius: 3,
      backgroundColor: theme.accent,
    },
    dateGroupTitle: {
      fontFamily: fonts.semiBold,
      fontSize: 14,
      lineHeight: 20,
      color: theme.textMuted,
      marginBottom: 8,
      marginTop: 4,
    },
    sessionCardTop: {
      flexDirection: "row",
      alignItems: "flex-start",
      justifyContent: "space-between",
      gap: 8,
      marginBottom: 6,
    },
    sessionTitle: {
      flex: 1,
      fontFamily: fonts.semiBold,
      fontSize: 17,
      lineHeight: 22,
      color: theme.text,
    },
    templateDescription: {
      fontFamily: fonts.regular,
      fontSize: 13,
      lineHeight: 18,
      color: theme.textMuted,
      marginTop: 2,
    },
    sessionMeta: {
      fontFamily: fonts.regular,
      fontSize: 13,
      lineHeight: 18,
      color: theme.textMuted,
      marginBottom: 2,
    },
    sessionSource: {
      fontFamily: fonts.regular,
      fontSize: 12,
      lineHeight: 16,
      color: theme.accent,
      marginBottom: 8,
    },
    statusPill: {
      alignSelf: "flex-start",
      paddingHorizontal: 10,
      paddingVertical: 4,
      borderRadius: 999,
      backgroundColor: theme.border,
      marginBottom: 12,
    },
    statusPillReady: {
      backgroundColor: theme.accentSoft,
    },
    statusPillText: {
      fontFamily: fonts.medium,
      fontSize: 12,
      lineHeight: 16,
      color: theme.textMuted,
    },
    statusPillTextReady: {
      color: theme.accent,
    },
    sessionActions: {
      flexDirection: "row",
      gap: 10,
    },
    actionButton: {
      flex: 1,
      paddingVertical: 10,
      borderRadius: 999,
      alignItems: "center",
      borderWidth: 1,
      borderColor: theme.border,
    },
    actionButtonPrimary: {
      backgroundColor: theme.accent,
      borderColor: theme.accent,
    },
    actionButtonText: {
      fontFamily: fonts.semiBold,
      fontSize: 14,
      lineHeight: 18,
      color: theme.text,
    },
    actionButtonTextPrimary: {
      color: "#fff",
    },
    emptyDay: {
      alignItems: "center",
      paddingVertical: 28,
      gap: 8,
    },
    emptyDayTitle: {
      fontFamily: fonts.semiBold,
      fontSize: 15,
      lineHeight: 20,
      color: theme.text,
      textAlign: "center",
    },
    emptyDaySub: {
      fontFamily: fonts.regular,
      fontSize: 13,
      lineHeight: 18,
      color: theme.textMuted,
      textAlign: "center",
      paddingHorizontal: 16,
    },
    templateMetaRow: {
      flexDirection: "row",
      flexWrap: "wrap",
      alignItems: "center",
      gap: 4,
      marginTop: 4,
      marginBottom: 0,
    },
    templateMetaItem: {
      flexDirection: "row",
      alignItems: "center",
      gap: 3,
    },
    templateMetaChip: {
      fontFamily: fonts.regular,
      fontSize: 12,
      lineHeight: 16,
      color: theme.textMuted,
    },
    templateMetaDot: {
      fontFamily: fonts.regular,
      fontSize: 12,
      lineHeight: 16,
      color: theme.textMuted,
      marginHorizontal: -1,
    },
    templateActions: {
      flexDirection: "row",
      gap: 6,
      marginTop: 8,
    },
    templateActionBtn: {
      flex: 1,
      paddingVertical: 9,
      borderRadius: 12,
      alignItems: "center",
      backgroundColor: theme.accentSoft,
    },
    templateActionText: {
      fontFamily: fonts.semiBold,
      fontSize: 13,
      color: theme.accent,
    },
    programRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
      paddingVertical: 12,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: theme.divider,
    },
    programWeekday: {
      width: 36,
      fontFamily: fonts.semiBold,
      fontSize: 13,
      lineHeight: 18,
      color: theme.textMuted,
      textTransform: "lowercase",
    },
    programBody: {
      flex: 1,
      minWidth: 0,
    },
    programTitle: {
      fontFamily: fonts.semiBold,
      fontSize: 15,
      lineHeight: 20,
      color: theme.text,
    },
    programTitleMuted: {
      color: theme.textMuted,
      fontFamily: fonts.regular,
    },
    programHint: {
      marginTop: 12,
      fontFamily: fonts.regular,
      fontSize: 13,
      lineHeight: 18,
      color: theme.textMuted,
    },
    programSectionHeader: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      marginBottom: 12,
    },
    programSectionLink: {
      fontFamily: fonts.semiBold,
      fontSize: 13,
      lineHeight: 18,
      color: theme.accent,
    },
    programCurrentCardHead: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      marginBottom: 4,
    },
    programCatalogCard: {
      borderRadius: PLAQUE_RADIUS,
      backgroundColor: theme.card,
      paddingHorizontal: 16,
      paddingVertical: 14,
      marginBottom: 10,
      ...plaqueListShadow(),
    },
    programCatalogCardExpanded: {
      paddingBottom: 12,
    },
    programCatalogHeader: {
      gap: 4,
    },
    programCatalogBody: {
      marginTop: 8,
      paddingTop: 8,
      borderTopWidth: StyleSheet.hairlineWidth,
      borderTopColor: theme.divider,
    },
    programCatalogCardCurrent: {
      borderWidth: 1,
      borderColor: theme.accentSoft,
    },
    programCatalogTitleRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 4,
    },
    programCatalogTitleInner: {
      flexDirection: "row",
      flexWrap: "wrap",
      alignItems: "center",
      gap: 8,
    },
    programCatalogTitle: {
      flexShrink: 1,
      fontFamily: fonts.semiBold,
      fontSize: 16,
      lineHeight: 21,
      color: theme.text,
    },
    programCatalogChevronHit: {
      width: 30,
      height: 30,
      alignItems: "center",
      justifyContent: "center",
    },
    programCatalogSummary: {
      marginTop: 4,
      fontFamily: fonts.regular,
      fontSize: 13,
      lineHeight: 18,
      color: theme.textMuted,
    },
    programCurrentBadge: {
      paddingHorizontal: 8,
      paddingVertical: 3,
      borderRadius: 999,
      backgroundColor: theme.accentSoft,
    },
    programCurrentBadgeText: {
      fontFamily: fonts.semiBold,
      fontSize: 11,
      lineHeight: 14,
      color: theme.accent,
    },
    comingSoonCard: {
      alignItems: "center",
      paddingVertical: 32,
      paddingHorizontal: 20,
      gap: 10,
    },
    comingSoonTitle: {
      fontFamily: fonts.semiBold,
      fontSize: 17,
      lineHeight: 22,
      color: theme.text,
      textAlign: "center",
    },
    comingSoonSub: {
      fontFamily: fonts.regular,
      fontSize: 14,
      lineHeight: 20,
      color: theme.textMuted,
      textAlign: "center",
    },
  });
}
