"""add_user_password_hash

Revision ID: 57e233f1f1b2
Revises: eacdd79b24e6
Create Date: 2026-03-13 13:04:47.642597

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "57e233f1f1b2"
down_revision: Union[str, Sequence[str], None] = "eacdd79b24e6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    conn = op.get_bind()

    # 1. Добавляем password_hash как nullable
    op.add_column("users", sa.Column("password_hash", sa.String(), nullable=True))

    # 2. Существующие пользователи — ставим placeholder (не смогут войти)
    conn.execute(
        sa.text(
            "UPDATE users SET password_hash = 'MIGRATION_PLACEHOLDER_NO_LOGIN' WHERE password_hash IS NULL"
        )
    )
    op.alter_column("users", "password_hash", existing_type=sa.String(), nullable=False)

    # 3. Email NOT NULL — для строк с NULL ставим placeholder
    conn.execute(
        sa.text(
            "UPDATE users SET email = 'legacy_' || id || '@migration.local' WHERE email IS NULL"
        )
    )
    op.alter_column("users", "email", existing_type=sa.VARCHAR(), nullable=False)
    op.drop_constraint("users_email_key", "users", type_="unique")
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.create_unique_constraint(
        op.f("users_email_key"),
        "users",
        ["email"],
        postgresql_nulls_not_distinct=False,
    )
    op.alter_column("users", "email", existing_type=sa.VARCHAR(), nullable=True)
    op.drop_column("users", "password_hash")
    # ### end Alembic commands ###
