"""auto_migration (deprecated)

Revision ID: 6ffb9e3113f3
Revises: eacdd79b24e6
Create Date: 2026-03-13 15:23:21.656038

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "6ffb9e3113f3"
down_revision: Union[str, Sequence[str], None] = "eacdd79b24e6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
