"""auto_migration (deprecated)

Revision ID: 8f5adc9c7945
Revises: 6ffb9e3113f3
Create Date: 2026-03-13 16:06:58.543759

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "8f5adc9c7945"
down_revision: Union[str, Sequence[str], None] = "6ffb9e3113f3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
