# Upstream для панелей (http-контекст; не включать внутрь server {})

upstream pgadmin_upstream {
    server pgadmin:80;
}

upstream grafana_upstream {
    server grafana:3000;
}

upstream prometheus_upstream {
    server prometheus:9090;
}

upstream redis_insight_upstream {
    server redis_gui:5540;
}

upstream maildev_upstream {
    server maildev:1080;
}
