# Редирект со старого habitpro.ru:9000 → https://habitpro.ru/… (порт 443)
server {
    listen 9000 ssl;
    http2 on;
    server_name habitpro.ru www.habitpro.ru;

    ssl_certificate /etc/letsencrypt/live/habitpro.ru/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/habitpro.ru/privkey.pem;
    ssl_session_timeout 1d;
    ssl_protocols TLSv1.2 TLSv1.3;

    return 301 https://$host$request_uri;
}
